controller_manager:
  ros__parameters:
    update_rate: 50

    diffdrive_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

diffdrive_controller:
  ros__parameters:
    left_wheel_names: ["left wheel"]
    right_wheel_names: ["right wheel"]

    wheel_separation: 0.33
    wheel_radius: 0.0975
    #odometry_topic: '/odom0'
    use_stamped_vel: false

joint_state_broadcaster:
  ros__parameters:
    extra_joints:
      - CASTER_WHEEL
      - casterWheelRim